export const data= {
  "DESCRIPTION":"Description",
  "OWNER":"Owner",
  "TRIGGER_EVENTS":"Trigger Events",
  "SELECT_ALL":"Select All",
  "SELECT_RECIPIENTS":"Select Recipients",
  "CLEAR_ALL":"Clear All",
  "ADDEDIT":"Add/Edit",
  "STANDARD":"Standard",
  "CUSTOME_Field":"Custome Field",
  "LEGAL_CODE":"Legal Code",
  "ADDITIONAL_OPT":"Additional Share and save Options",
  "CREATE":"Create",
  "CANCEL":"Cancel",
  "SAVE_DEFAULTS":"Save those ass my Default Settings",
  "SHARE_PUBLIC":"Share via Public Folder",
  "SAVE_PERSONAL":"Save to Personal Folder",
  "SHARE_INBOX":"Share via Saved work Inbox",
  "SHARE_MAIL":"Share via email",
  "TRACKSUBTITLE":"Select Client Reference For Tracking",
  "NOCLIENTREF":"No Client Reference Associated With this Watch",
  "USERECREF":"Use Recent Client Reference",
  "SETNEWREF":"Set new client reference",
  "SETCLIENTSEG":"Set client Segment",
  "SETPROJSEG":"Set project Segment",
  "SETSUBPROJSEG":"Set subproject Segment",
  "NEWCLI":"Or enter new client",
  "NEWPROJ":"Or enter new project",
  "NEWSUBPROJ":"Or enter new subproject"
}